Added lab1
Yoqeu/Android-Labs pull request #1
Opened 2021-01-10 15:05 UTC by Yoqeu

2021-01-10 19:49 UTC, gmltA requested changes

2021-01-10 19:49 UTC, gmltA commented on app/build.gradle
> +        versionName "1.0"
Task is not completed.

2021-01-10 20:49 UTC, Yoqeu commented on app/build.gradle
> +        versionName "1.0"
Fixed.

2021-01-28 11:01 UTC, gmltA approved these changes

2021-01-28 23:49 UTC, merged